// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwoQmju7VsB6WlL-f2Fw85iPN1PvXlMV4',
    appId: '1:586330510232:web:d4c973ddbfb4088e2211ed',
    messagingSenderId: '586330510232',
    projectId: 'shopping-list-c6d4a',
    authDomain: 'shopping-list-c6d4a.firebaseapp.com',
    storageBucket: 'shopping-list-c6d4a.appspot.com',
    measurementId: 'G-1WJH93VLLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TqpsPDkSoVCjBFsM1CahdszZMkI4uWI',
    appId: '1:586330510232:android:f0ca3bd7584abc672211ed',
    messagingSenderId: '586330510232',
    projectId: 'shopping-list-c6d4a',
    storageBucket: 'shopping-list-c6d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6pk1FjDZuDdo8MkP2tyv5YZdG12kFgA',
    appId: '1:586330510232:ios:ff81f8c78922a2e32211ed',
    messagingSenderId: '586330510232',
    projectId: 'shopping-list-c6d4a',
    storageBucket: 'shopping-list-c6d4a.appspot.com',
    iosBundleId: 'com.example.learnFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV6pk1FjDZuDdo8MkP2tyv5YZdG12kFgA',
    appId: '1:586330510232:ios:31a9d11b620270fe2211ed',
    messagingSenderId: '586330510232',
    projectId: 'shopping-list-c6d4a',
    storageBucket: 'shopping-list-c6d4a.appspot.com',
    iosBundleId: 'com.example.learnFirebase.RunnerTests',
  );
}
